name: Linux (clang++-14 | Ubuntu 22.04)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: CMake 
      run: cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -S . -B build-clang
    - name: Build
      run: cmake --build build-clang
    - name: Test
      run: build-clang/test/cartocrow_test
